name: "4lch4/Replace Tokens"
description: "Replace Strings (Tokens) w/in File(s)"
author: "4lch4"
outputs:
  replaceCount:
    description: The number of times a token was replaced.
branding:
  icon: at-sign
  color: green
inputs:
  tokenPrefix:
    required: false
    description: "The beginning of a token to replace."
    default: "#{"
  tokenSuffix:
    required: false
    description: "The ending of a token to replace."
    default: "}#"
  files:
    required: true
    description: "Glob expression, file name, or array of glob/file name"
    default: "#{"
runs:
  using: "node12"
  main: "dist/index.js"
